new work

diff --git a/load_balancer/0-custom_http_response_header b/load_balancer/0-custom_http_response_header
--- a/load_balancer/0-custom_http_response_header
+++ b/load_balancer/0-custom_http_response_header
@@ -1,39 +1,22 @@
 #!/usr/bin/env bash
-# Creating a server with a redirect
+# Configure Nginx with custom HTTP header
 
-# Updating all packages
-sudo apt-get update -y && sudo apt-get upgrade -y
+# Update and install Nginx
+sudo apt update -y
+sudo apt install nginx -y
 
-# Install Nginx
-sudo apt-get install nginx -y
+# code to add header to display hostname
+string_for_replacement="server_name _;\n\tadd_header X-Served-By \$hostname;"
+sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default
 
-# Creating an index page
-echo "Holberton School" | sudo tee /var/www/html/index.html
+# Test Nginx configuration
+sudo nginx -t
 
-# Creating a 404 page
-echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
-
-# Write data to nginx.conf
-echo "
-events {
-
-}
-
-http {
-	server {
-		listen 80;
-
-		root /var/www/html;
-
-		error_page 404 /404.html;
-
-		add_header X-Served-By \$hostname;
-
-		location /redirect_me {
-			return 301 https://google.com;
-		}
-	}
-}" | sudo tee /etc/nginx/nginx.conf
-
-# Reload nginx
-sudo service nginx restart
+# If the test is successful, restart Nginx
+if [ $? -eq 0 ]; then
+    sudo service nginx restart
+    echo "Nginx configuration updated and restarted successfully."
+else
+    echo "Nginx configuration test failed. Please check the configuration."
+    exit 1
+fi
